---
- name: Create user
  hosts: localhost
  become: yes
  vars_files:
    - user_list.yml
  tasks:
    - name: Create users
      vars:
        password: "{{ lookup('password', './{{ item.name }}-passwordfile.txt length=6') }}"
      user:
        name: "{{ item.name }}"
        uid: "{{ item.uid }}"
        comment: "{{ item.first | capitalize }} {{ item.middle | capitalize }} {{ item.last | capitalize }}"
        password: "{{ password | password_hash('sha512')}}"
        shell: /bin/shell
        update_password: on_create
        state: present
      with_items: "{{ users }}"
...      
